### ISSUE TITLE
Remove `tester_index` from converter

### ISSUE THREAD

**Issue by leonardhyu** [xenanetworks/open-automation-config-converter#10]
The `port_identities` should be like:

```
"port_identities": [
        {
            "tester_id": "66819eb076c5cd6901fa214d0685c8cf",
            "module_index": 1,
            "port_index": 0
        },
        {
            "tester_id": "66819eb076c5cd6901fa214d0685c8cf",
            "module_index": 1,
            "port_index": 1
        }
    ],
```

**Comment by RonDingDing** [comment]
Because the index is gone now, no one knows which is which when specifying port_config, port_slot_config, peer_config and peer_config, need to add a ```[{'key': port_config, 'value': peer_config}]``` map to serve as a mapping. In the port configuration, there should only be a port_slot_config, while you only need to change the map to refer to another real port.
